2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_setup.py:_flush():68] Configure stats pid to 289727
2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_setup.py:_flush():68] Loading settings from /home/ckqsudo/.config/wandb/settings
2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_setup.py:_flush():68] Loading settings from /home/ckqsudo/code2024/CKQ_ACL2024/Control_Infer/SAE-simple/src/debate_test/wandb/settings
2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-22 00:39:29,302 INFO    MainThread:289727 [wandb_init.py:_log_setup():528] Logging user logs to /home/ckqsudo/code2024/CKQ_ACL2024/Control_Infer/SAE-simple/src/debate_test/wandb/run-20250122_003929-g6dh9gb8/logs/debug.log
2025-01-22 00:39:29,303 INFO    MainThread:289727 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ckqsudo/code2024/CKQ_ACL2024/Control_Infer/SAE-simple/src/debate_test/wandb/run-20250122_003929-g6dh9gb8/logs/debug-internal.log
2025-01-22 00:39:29,303 INFO    MainThread:289727 [wandb_init.py:init():644] calling init triggers
2025-01-22 00:39:29,303 INFO    MainThread:289727 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2025-01-22 00:39:29,303 INFO    MainThread:289727 [wandb_init.py:init():680] starting backend
2025-01-22 00:39:29,303 INFO    MainThread:289727 [wandb_init.py:init():684] sending inform_init request
2025-01-22 00:39:29,310 INFO    MainThread:289727 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-22 00:39:29,310 INFO    MainThread:289727 [wandb_init.py:init():697] backend started and connected
2025-01-22 00:39:29,313 INFO    MainThread:289727 [wandb_init.py:init():790] updated telemetry
2025-01-22 00:39:29,322 INFO    MainThread:289727 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-22 00:39:29,322 WARNING MsgRouterThr:289727 [router.py:message_loop():75] message_loop has been closed
2025-01-22 00:39:34,325 ERROR   MainThread:289727 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
